bluelog/blueprints/admin.py
import os

from flask import Blueprint, render_template, flash, request, current_app, redirect, url_for, send_from_directory
from flask_ckeditor import upload_fail, upload_success
from flask_login import login_required, current_user

from bluelog.extensions import db
from bluelog.forms import SettingForm, PostForm, CategoryForm, UpdateCategoryForm, LinkForm
from bluelog.models import Post, Category, Comment, Link
from bluelog.utils import redirect_back, allowed_file

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('保存成功!', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about

    return render_template('admin/settings.html', form=form)


@admin_bp.route('/post/manage')
@login_required
def manage_post():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('admin/manage_post.html', pagination=pagination, posts=posts)


@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        category = Category.query.get_or_404(int(form.category.data))
        post = Post(title=form.title.data, body=form.body.data, category=category)
        # post.slug = form.slug.data
        db.session.add(post)
        db.session.commit()
        flash('博客已保存', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    if request.args.get('category'):
        form.category.data = request.args.get('category', 1, type=int)
    return render_template('admin/new_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.category = Category.query.get_or_404(int(form.category.data))
        db.session.commit()
        flash('博客已更新', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    form.title.data = post.title
    form.category.data = post.category_id
    form.body.data = post.body
    return render_template('admin/edit_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('博客已删除', 'success')
    return redirect_back()


@admin_bp.route('/category/manage')
@login_required
def manage_category():
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data)
        db.session.add(category)
        db.session.commit()
        flash('分类已保存', 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
    category = Category.query.get_or_404(category_id)
    form = UpdateCategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('分类已修改', 'success')
        return redirect(url_for('.manage_category'))
    form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    if category_id == 1:
        flash('默认分类不能删除')
        return redirect(url_for('blog.index'))
    category = Category.query.get_or_404(category_id)
    category.delete()
    flash('分类已删除', 'success')
    return redirect_back()


@admin_bp.route('/comment/manage', defaults={'filter_url': 'all'})
@admin_bp.route('/comment/manage/<any(unread, admin, all):filter_url>')
@login_required
def manage_comment(filter_url):
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_COMMENT_PER_PAGE']
    # filter_url = request.args.get('filter', 'all')
    if not filter_url:
        filter_url = 'all'
    if filter_url == 'unread':
        filter_comment = Comment.query.filter_by(reviewed=False)
    elif filter_url == 'admin':
        filter_comment = Comment.query.filter_by(from_admin=True)
    else:
        filter_comment = Comment.query
    pagination = filter_comment.order_by(Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments=comments, pagination=pagination, filter_url=filter_url)


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('评论已删除', 'success')
    return redirect_back()


@admin_bp.route('/set_comment/<int:post_id>', methods=['POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('评论已关闭!', 'info')
    else:
        post.can_comment = True
        flash('评论已打开!', 'info')
    db.session.commit()
    return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
@login_required
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    flash('评论通过', 'success')
    return redirect_back()


@admin_bp.route('/link/manage')
@login_required
def manage_link():
    return render_template('admin/manage_link.html')


@admin_bp.route('link/new', methods=['GET', 'POST'])
@login_required
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        link = Link(name=form.name.data, url=form.url.data)
        db.session.add(link)
        db.session.commit()
        flash('添加连接成功', 'success')
        return redirect(url_for('.manage_link'))
    return render_template('admin/new_link.html', form=form)


@admin_bp.route('link/<int:link_id>/editor', methods=['GET', 'POST'])
@login_required
def editor_link(link_id):
    link = Link.query.get_or_404(link_id)
    form = LinkForm()
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        db.session.commit()
        flash('连接修改成功', 'success')
        return redirect(url_for('.manage_link'))
    form.name.data = link.name
    form.url.data = link.url
    return render_template('admin/edit_link.html', form=form)


@admin_bp.route('link/<int:link_id>delete', methods=['GET', 'POST'])
@login_required
def delete_link(link_id):
    link = Link.query.get_or_404(link_id)
    db.session.delete(link)
    db.session.commit()
    flash('连接已删除', 'success')
    return redirect_back()


@admin_bp.route('/upload/<path:filepath>')
def get_upload(filepath):
    return send_from_directory(current_app.config['BLOG_UPLOAD_PATH'], filename=filepath)


@admin_bp.route('/upload', methods=['POST'])
@login_required
def upload_image():
    f = request.files.get('upload')
    if not allowed_file(f.filename):
        return upload_fail('只能上传jpg, jpeg, gif, png格式的图片')
    f.save(os.path.join(current_app.config['BLOG_UPLOAD_PATH'], f.filename))
    url = url_for('.get_upload', filepath=f.filename)
    return upload_success(url, f.filename)

bluelog/blueprints/auth.py
from flask import Blueprint, redirect, url_for, flash, render_template
from flask_login import current_user, login_user, logout_user, login_required

from bluelog import Admin
from bluelog.forms import LoginForm
from bluelog.utils import redirect_back

auth_bp = Blueprint('auth', __name__)


@auth_bp.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('blog.index'))
    form = LoginForm()
    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        remember = form.remember.data

        admin = Admin.query.first()
        if admin:
            if admin.username == username and admin.validate_password(password):
                login_user(admin, remember=remember)
                flash('欢迎回来', 'info')
                return redirect_back()
            flash('用户名或密码错误', 'warning')
        else:
            flash('没有用户', 'warning')
    return render_template('auth/login.html', form=form)


@auth_bp.route('/logout')
@login_required
def logout():
    logout_user()
    flash('退出成功', 'info')
    return redirect(url_for('blog.index'))

bluelog/templates/_macros.html
{% macro nav_link(endpoint, text) %}
    <li class="nav-item{% if request.endpoint and request.endpoint== endpoint %}active{% endif %}">
        <a href="{{ url_for(endpoint, **kwargs) }}" class="nav-link">{{ text }}</a>
    </li>
{% endmacro %}


{% macro pager(pagination, fragment='') %}
    <nav aria-label="Page navigation">
        <ul class="pagination">
            <li class="page-item {% if not pagination.has_prev %}disabled{% endif %}">
                <a class="page-link"
                   href="{{ url_for(request.endpoint, page=pagination.prev_num, **kwargs) + fragment if pagination.has_prev else '#' }}">
                    <span aria-hidden="true">&larr;</span>上一页
                </a>
            </li>
            <li class="page-item {% if not pagination.has_next %}disabled{% endif %}">
                <a class="page-link"
                   href="{{ url_for(request.endpoint, page=pagination.next_num, **kwargs) + fragment if pagination.has_next else '#' }}">
                    <span aria-hidden="true">&rarr;</span>下一页
                </a>
            </li>
        </ul>
    </nav>
{% endmacro %}

bluelog/templates/base.html
{% from 'bootstrap/nav.html' import render_nav_item %}
<!doctype html>
<html lang="zh">
<head>
    {% block head %}
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0, shrink-to-fit=no">
        <title>{% block title %}{% endblock title %}</title>
        <link rel="icon" href="{{ url_for('static', filename='favicon.ico') }}">
        <link rel="stylesheet"
              href="{{ url_for('static', filename='css/%s.min.css' % request.cookies.get('theme', 'default')) }}"
              type="text/css">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}" type="text/css">
    {% endblock head %}
</head>
<body>
{% block nav %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="container">
            <a class="navbar-brand" href="/">Blog</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01"
                    aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarColor01">
                <ul class="navbar-nav mr-auto">
                    {{ render_nav_item('blog.index', "主页") }}
                    {{ render_nav_item('blog.about', '关于') }}
                </ul>
                <ul class="nav navbar-nav">
                    {% if current_user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">新建{# <span class="caret"></span> #}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.new_post') }}">博客</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_category') }}">分类</a>
                                <a class="dropdown-item" href="{{ url_for('admin.new_link') }}">连接</a>
                            </div>
                        </li>
                        <li class="nav-item dropdown">
                            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">管理{# <span class="caret"></span> #}
                                {% if unread_comments %}
                                    <span class="badge badge-success">new</span>
                                {% endif %}
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ url_for('admin.manage_post') }}">博客</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_category') }}">分类</a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_comment') }}">评论
                                {% if unread_comments %}
                                    <span class="badge badge-info">{{ unread_comments }}</span>
                                {% endif %}
                                </a>
                                <a class="dropdown-item" href="{{ url_for('admin.manage_link') }}">连接</a>
                            </div>
                        </li>
                        {{ render_nav_item('admin.settings', '设置') }}
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
{% endblock %}
<main class="container">
    {% for message in get_flashed_messages(with_categories=True) %}
        <div class="alert alert-{{ message[0] }}" role="alert">
            <button type="button" class="close" data-dismiss="alert">&times;</button>
            {{ message[1] }}
        </div>
    {% endfor %}

    {% block content %}{% endblock %}

    {% block footer %}
        <footer>
            <small>&copy; 2019</small>
            <small class="float-right">
                {% if current_user.is_authenticated %}
                    <a href="{{ url_for('auth.logout', next=request.full_path) }}">退出</a>
                {% else %}
                    <a href="{{ url_for('auth.login', next=request.full_path) }}">登陆</a>
                {% endif %}
            </small>
        </footer>
    {% endblock %}
</main>
{% block scripts %}
    <script type="text/javascript" src="{{ url_for('static', filename='js/jquery-3.3.1.slim.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/popper.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/clipboard.min.js') }}"></script>
    <script type="text/javascript" src="{{ url_for('static', filename='js/script.js') }}"></script>
    {{ moment.include_moment(local_js=url_for('static', filename='js/moment-with-locales.min.js')) }}
    {{ moment.locale('zh-CN') }}
{% endblock %}
</body>
</html>