bluelog/blueprints/admin.py
import os

from flask import Blueprint, render_template, flash, request, current_app, redirect, url_for, send_from_directory
from flask_ckeditor import upload_fail, upload_success
from flask_login import login_required, current_user

from bluelog.extensions import db
from bluelog.forms import SettingForm, PostForm, CategoryForm, UpdateCategoryForm, LinkForm
from bluelog.models import Post, Category, Comment, Link
from bluelog.utils import redirect_back, allowed_file

admin_bp = Blueprint('admin', __name__)


@admin_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = SettingForm()
    if form.validate_on_submit():
        current_user.name = form.name.data
        current_user.blog_title = form.blog_title.data
        current_user.blog_sub_title = form.blog_sub_title.data
        current_user.about = form.about.data
        db.session.commit()
        flash('保存成功!', 'success')
        return redirect(url_for('blog.index'))
    form.name.data = current_user.name
    form.blog_title.data = current_user.blog_title
    form.blog_sub_title.data = current_user.blog_sub_title
    form.about.data = current_user.about

    return render_template('admin/settings.html', form=form)


@admin_bp.route('/post/manage')
@login_required
def manage_post():
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page)
    posts = pagination.items
    return render_template('admin/manage_post.html', pagination=pagination, posts=posts)


@admin_bp.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        category = Category.query.get_or_404(int(form.category.data))
        post = Post(title=form.title.data, body=form.body.data, category=category)
        # post.slug = form.slug.data
        db.session.add(post)
        db.session.commit()
        flash('博客已保存', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    if request.args.get('category'):
        form.category.data = request.args.get('category', 1, type=int)
    return render_template('admin/new_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_post(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.body = form.body.data
        post.category = Category.query.get_or_404(int(form.category.data))
        db.session.commit()
        flash('博客已更新', 'success')
        return redirect(url_for('blog.show_post', post_id=post.id))
    form.title.data = post.title
    form.category.data = post.category_id
    form.body.data = post.body
    return render_template('admin/edit_post.html', form=form)


@admin_bp.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get_or_404(post_id)
    db.session.delete(post)
    db.session.commit()
    flash('博客已删除', 'success')
    return redirect_back()


@admin_bp.route('/category/manage')
@login_required
def manage_category():
    return render_template('admin/manage_category.html')


@admin_bp.route('/category/new', methods=['GET', 'POST'])
@login_required
def new_category():
    form = CategoryForm()
    if form.validate_on_submit():
        category = Category(name=form.name.data)
        db.session.add(category)
        db.session.commit()
        flash('分类已保存', 'success')
        return redirect(url_for('.manage_category'))
    return render_template('admin/new_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/edit', methods=['GET', 'POST'])
@login_required
def edit_category(category_id):
    category = Category.query.get_or_404(category_id)
    form = UpdateCategoryForm()
    if form.validate_on_submit():
        category.name = form.name.data
        db.session.commit()
        flash('分类已修改', 'success')
        return redirect(url_for('.manage_category'))
    form.name.data = category.name
    return render_template('admin/edit_category.html', form=form)


@admin_bp.route('/category/<int:category_id>/delete', methods=['POST'])
@login_required
def delete_category(category_id):
    if category_id == 1:
        flash('默认分类不能删除')
        return redirect(url_for('blog.index'))
    category = Category.query.get_or_404(category_id)
    category.delete()
    flash('分类已删除', 'success')
    return redirect_back()


@admin_bp.route('/comment/manage', defaults={'filter_url': 'all'})
@admin_bp.route('/comment/manage/<any(unread, admin, all):filter_url>')
@login_required
def manage_comment(filter_url):
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_MANAGE_COMMENT_PER_PAGE']
    # filter_url = request.args.get('filter', 'all')
    if not filter_url:
        filter_url = 'all'
    if filter_url == 'unread':
        filter_comment = Comment.query.filter_by(reviewed=False)
    elif filter_url == 'admin':
        filter_comment = Comment.query.filter_by(from_admin=True)
    else:
        filter_comment = Comment.query
    pagination = filter_comment.order_by(Comment.timestamp.desc()).paginate(page, per_page)
    comments = pagination.items
    return render_template('admin/manage_comment.html', comments=comments, pagination=pagination, filter_url=filter_url)


@admin_bp.route('/comment/<int:comment_id>/delete', methods=['POST'])
@login_required
def delete_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    db.session.delete(comment)
    db.session.commit()
    flash('评论已删除', 'success')
    return redirect_back()


@admin_bp.route('/set_comment/<int:post_id>', methods=['POST'])
@login_required
def set_comment(post_id):
    post = Post.query.get_or_404(post_id)
    if post.can_comment:
        post.can_comment = False
        flash('评论已关闭!', 'info')
    else:
        post.can_comment = True
        flash('评论已打开!', 'info')
    db.session.commit()
    return redirect_back()


@admin_bp.route('/comment/<int:comment_id>/approve', methods=['POST'])
@login_required
def approve_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    comment.reviewed = True
    db.session.commit()
    flash('评论通过', 'success')
    return redirect_back()


@admin_bp.route('/link/manage')
@login_required
def manage_link():
    return render_template('admin/manage_link.html')


@admin_bp.route('link/new', methods=['GET', 'POST'])
@login_required
def new_link():
    form = LinkForm()
    if form.validate_on_submit():
        link = Link(name=form.name.data, url=form.url.data)
        db.session.add(link)
        db.session.commit()
        flash('添加连接成功', 'success')
        return redirect(url_for('.manage_link'))
    return render_template('admin/new_link.html', form=form)


@admin_bp.route('link/<int:link_id>/editor', methods=['GET', 'POST'])
@login_required
def editor_link(link_id):
    link = Link.query.get_or_404(link_id)
    form = LinkForm()
    if form.validate_on_submit():
        link.name = form.name.data
        link.url = form.url.data
        db.session.commit()
        flash('连接修改成功', 'success')
        return redirect(url_for('.manage_link'))
    form.name.data = link.name
    form.url.data = link.url
    return render_template('admin/edit_link.html', form=form)


@admin_bp.route('link/<int:link_id>delete', methods=['GET', 'POST'])
@login_required
def delete_link(link_id):
    link = Link.query.get_or_404(link_id)
    db.session.delete(link)
    db.session.commit()
    flash('连接已删除', 'success')
    return redirect_back()


@admin_bp.route('/upload/<path:filepath>')
def get_upload(filepath):
    return send_from_directory(current_app.config['BLOG_UPLOAD_PATH'], filename=filepath)


@admin_bp.route('/upload', methods=['POST'])
@login_required
def upload_image():
    f = request.files.get('upload')
    if not allowed_file(f.filename):
        return upload_fail('只能上传jpg, jpeg, gif, png格式的图片')
    f.save(os.path.join(current_app.config['BLOG_UPLOAD_PATH'], f.filename))
    url = url_for('.get_upload', filepath=f.filename)
    return upload_success(url, f.filename)

bluelog/blueprints/blog.py
from flask import Blueprint, render_template, request, current_app, url_for, flash, redirect, abort, make_response
from flask_login import current_user

from bluelog.emails import send_new_comment_email, send_new_reply_email
from bluelog.forms import AdminCommentForm, CommentForm
from bluelog.models import Post, Category, Comment
from bluelog.extensions import db
from bluelog.utils import redirect_back

blog_bp = Blueprint('blog', __name__)


@blog_bp.route('/', defaults={'page': 1})
@blog_bp.route('/page/<int:page>')
def index(page):
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.order_by(Post.timestamp.desc()).paginate(page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/index.html', posts=posts, pagination=pagination)


@blog_bp.route('/about')
def about():
    return render_template('blog/about.html')


@blog_bp.route('/category/<int:category_id>')
def show_category(category_id):
    category = Category.query.get_or_404(category_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_POST_PER_PAGE']
    pagination = Post.query.with_parent(category).order_by(Post.timestamp.desc()).paginate(
        page=page, per_page=per_page)
    posts = pagination.items
    return render_template('blog/category.html', pagination=pagination, posts=posts, category=category)


@blog_bp.route('/post/<int:post_id>', methods=['GET', 'POST'])
def show_post(post_id):
    post = Post.query.get_or_404(post_id)
    page = request.args.get('page', 1, type=int)
    per_page = current_app.config['BLOG_COMMENT_PER_PAGE']
    pagination = Comment.query.with_parent(post).filter_by(reviewed=True).order_by(Comment.timestamp.desc()).paginate(
        page=page,
        per_page=per_page)
    comments = pagination.items

    if current_user.is_authenticated:
        form = AdminCommentForm()
        form.author.data = current_user.name
        form.email.data = current_app.config['BLOG_ADMIN_EMAIL']
        form.site.data = url_for('.index')
        from_admin = True
        reviewed = True
    else:
        form = CommentForm()
        from_admin = False
        reviewed = True

    if form.validate_on_submit():
        author = form.author.data
        email = form.email.data
        site = form.site.data
        body = form.body.data
        comment = Comment(author=author, email=email, site=site, body=body, from_admin=from_admin, reviewed=reviewed,
                          post=post)
        replied_id = request.args.get('reply')
        if replied_id:
            replied_comment = Comment.query.get_or_404(replied_id)
            comment.replied = replied_comment
            send_new_reply_email(replied_comment)
        db.session.add(comment)
        db.session.commit()

        if current_user.is_authenticated:
            flash('评论以发布', 'success')
        else:
            flash('感谢你的精彩点评, 我们将在审核之后发布评论.', 'info')
            send_new_comment_email(post)
        return redirect(url_for('.show_post', post_id=post.id))
    return render_template('blog/post.html', post=post, comments=comments, pagination=pagination, form=form)


@blog_bp.route('/reply/comment/<int:comment_id>')
def reply_comment(comment_id):
    comment = Comment.query.get_or_404(comment_id)
    if comment.post.can_comment:
        return redirect(
            url_for('.show_post', post_id=comment.post_id, reply=comment_id, author=comment.author) + '#comment-form')
    flash('这篇博客禁止评论', 'danger')
    return redirect_back()


@blog_bp.route('/change-theme/<theme_name>')
def change_theme(theme_name):
    if theme_name not in current_app.config['BLOG_THEMES'].keys():
        abort(404)
    response = make_response(redirect_back())
    response.set_cookie('theme', theme_name, max_age=60 * 60 * 24 * 30)
    return response

# @blog_bp.route('/post_slug/<slug>')
# def show_post_slug(slug):
#     post = Post.query.filter_by(slug=slug).first_or_404()
#     return render_template('blog/post.html', post=post)

bluelog/templates/blog/_posts.html
{% if posts %}
    {% for post in posts %}
        <h3 class="text-primary"><a href="{{ url_for('.show_post', post_id=post.id) }}">{{ post.title }}</a>
        </h3>
        <p>
            {{ post.body|striptags|truncate }}
            <small><a href="{{ url_for('.show_post', post_id=post.id) }}">更多</a></small>
        </p>
        <small>
            Comments: <a
                href="{{ url_for('.show_post', post_id=post.id) }}#comments">{{ post.comments|length }}</a>&nbsp;&nbsp;
            Category: <a
                href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
            <span class="float-right">{{ moment(post.timestamp).format('LL') }}</span>
        </small>
        {% if not loop.last %}
            <hr>
        {% endif %}
    {% endfor %}
{% else %}
    <div class="tip">
        {% if category %}
            <h5>这个分类下没有博客</h5>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('admin.new_post', category=category.id) }}">写一份</a>
            {% endif %}
        {% else %}
            <h5>没有博客</h5>
            {% if current_user.is_authenticated %}
                <a href="{{ url_for('admin.new_post') }}">写一份</a>
            {% endif %}
        {% endif %}

    </div>
{% endif %}

bluelog/templates/blog/_sidebar.html
{% if links %}
    <div class="card mb-3">
        <div class="card-header">连接</div>
        <ul class="list-group list-group-flush">
            {% for link in links %}
                <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ link.url }}" target="_blank">{{ link.name }}</a>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

{% if categories %}
    <div class="card mb-3">
        <div class="card-header">分类</div>
        <ul class="list-group list-group-flush">
            {% for category in categories %}
                <li class="list-group-item list-group-item-action d-flex justify-content-between align-items-center">
                    <a href="{{ url_for('blog.show_category', category_id=category.id) }}">{{ category.name }}</a>
                    <span class="badge badge-primary badge-pill">{{ category.posts|length }}</span>
                </li>
            {% endfor %}
        </ul>
    </div>
{% endif %}

<div class="dropdown">
    <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">切换主题
    </button>
    <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
        {% for theme_name, display_name in config.BLOG_THEMES.items() %}
            <a class="dropdown-item" href="{{ url_for('blog.change_theme', theme_name=theme_name, next=request.full_path) }}">{{ display_name }}</a>
        {% endfor %}

    </div>
</div>

bluelog/templates/blog/about.html
{% extends 'base.html' %}

{% block title %}关于{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>关于</h1>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ admin.about|safe }}
        </div>
        <div class="col-sm-4 sidebar">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

bluelog/templates/blog/category.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}分类-{{ category.name }}{% endblock %}


{% block content %}
    <div class="page-header">
        <h1>{{ category.name }}</h1>
        <h4 class="text-muted">共{{ category.posts|length }}个博客</h4>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include 'blog/_posts.html' %}
            {% if posts %}
                <div class="page-footer">{{ render_pagination(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-sm-4">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

bluelog/templates/blog/index.html
{% extends 'base.html' %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}主页{% endblock %}

{% block content %}
    <div class="page-header">
        <h1 class="display-3">{{ admin.blog_title|default('Blog Title') }}</h1>
        <h4 class="text-muted">&nbsp;{{ admin.blog_sub_title|default('Blog Subtitle') }}</h4>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {% include 'blog/_posts.html' %}
            {% if posts %}
                <div class="page-footer">{{ render_pagination(pagination) }}</div>
            {% endif %}
        </div>
        <div class="col-sm-4">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

bluelog/templates/blog/post.html
{% extends 'base.html' %}
{% from 'bootstrap/form.html' import render_form %}
{% from 'bootstrap/pagination.html' import render_pagination %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <div class="page-header">
        <h1>{{ post.title }}
            <span class="float-right">
            {% if current_user.is_authenticated %}
                <a class="btn btn-info btn-sm" href="{{ url_for('admin.edit_post', post_id=post.id) }}">编辑</a>
                <form class="inline" method="post"
                      action="{{ url_for('admin.delete_post', post_id=post.id, next=url_for('blog.index')) }}">
                    <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                    <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm('确定删除吗?');">删除</button>
                </form>
            {% endif %}
            </span>
        </h1>
        <small>
            分类: <a href="{{ url_for('.show_category', category_id=post.category.id) }}">{{ post.category.name }}</a>
            <br>
            时间: {{ moment(post.timestamp).format('LL') }}
        </small>
    </div>
    <div class="row">
        <div class="col-sm-8">
            {{ post.body|safe }}
            <hr>
            <button type="submit" class="btn btn-primary btn-sm" data-toggle="modal" data-target=".postLinkModal">分享
            </button>

            <div class="modal fade postLinkModal" tabindex="-1" role="dialog" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h5 class="modal-title">分享连接</h5>
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                                    aria-hidden="true">&times;</span></button>
                        </div>
                        <div class="modal-body">
                            <div class="form-group">
                                <input id="share" type="text" data-clipboard-target="#share" class="form-control c-btn"
                                       value="{{ url_for('.show_post', post_id=post.id, _external=True) }}" readonly>
                            </div>
                            <div class="bdsharebuttonbox form-group float-right">
                                <a href="#" class="bds_more" data-cmd="more"></a>
                                <a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a>
                                <a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a>
                                <a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a>
                                <a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a>
                                <a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments" id="comments">
                <h3>{{ pagination.total }}条评论
                    <small>
                        <a href="{{ url_for('.show_post', post_id=post.id, page=pagination.pages or 1) }}#comments">latest</a>
                    </small>
                    {% if current_user.is_authenticated %}
                        <form class="float-right"
                              action="{{ url_for('admin.set_comment',post_id=post.id, next=request.full_path) }}"
                              method="post">
                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                            <button type="submit" class="btn btn-warning btn-sm">{% if post.can_comment %}关闭{% else %}
                                打开{% endif %}评论
                            </button>
                        </form>
                    {% endif %}
                </h3>
                {% if comments %}
                    <ul class="list-group">
                        {% for comment in comments %}
                            <li class="list-group-item list-group-item-action flex-column">
                                <div class="d-flex w-100 justify-content-between">
                                    <h5 class="mb-1">
                                        <a href="{% if comment.site %}{{ comment.site }}{% else %}#{% endif %}"
                                           target="_blank">
                                            {% if comment.from_admin %}
                                                {{ admin.name }}
                                            {% else %}
                                                {{ comment.author }}
                                            {% endif %}
                                        </a>
                                        {% if comment.from_admin %}
                                            <span class="badge badge-primary">作者</span>{% endif %}
                                        {% if comment.replied %}<span class="badge badge-light">回复</span>{% endif %}
                                    </h5>
                                    <small data-toggle="tooltip" data-placement="top" data-delag="500"
                                           data-timestamp="{{ comment.timestamp.strftime('%Y-%m-%dT%H:%M:%SZ') }}">{{ moment(comment.timestamp).fromNow() }}</small>
                                </div>
                                {% if comment.replied %}
                                    <p class="alert alert-dark reply-body">{{ comment.replied.author }}<br>{{ comment.replied.body }}
                                    </p>
                                {% endif %}
                                <p class="mb-1">{{ comment.body }}</p>
                                <div class="float-right">
                                    <a class="btn btn-light btn-sm"
                                       href="{{ url_for('.reply_comment', comment_id=comment.id, next=request.full_path) }}">评论</a>
                                    {% if current_user.is_authenticated %}
                                        <a class="btn btn-light btn-sm" href="mailto:{{ comment.email }}">Email</a>
                                        <form class="inline"
                                              action="{{ url_for('admin.delete_comment', comment_id=comment.id, next=request.full_path) }}"
                                              method="post">
                                            <input type="hidden" name="csrf_token" value="{{ csrf_token() }}">
                                            <button type="submit" class="btn btn-danger btn-sm"
                                                    onclick="return confirm('确定删除吗?');">删除
                                            </button>
                                        </form>
                                    {% endif %}
                                </div>
                            </li>
                        {% endfor %}
                    </ul>
                {% else %}
                    <div class="tip"><h5>没有评论</h5></div>
                {% endif %}
            </div>
            {% if comments %}
                {{ render_pagination(pagination, fragment='#comments') }}
            {% endif %}
            {% if post.can_comment %}
                {% if request.args.get('reply') %}
                    <div class="alert alert-dark">回复<strong>{{ request.args.get('author') }}</strong>:
                        <a class="float-right" href="{{ url_for('.show_post', post_id=post.id) }}">取消</a>
                    </div>
                {% endif %}
                <div id="comment-form">
                    {{ render_form(form, action=request.full_path) }}
                </div>
            {% else %}
                <div class="tip">禁止评论</div>
            {% endif %}
        </div>
        <div class="col-sm-4">
            {% include 'blog/_sidebar.html' %}
        </div>
    </div>
{% endblock %}

{% block scripts %}
    <script>
        window._bd_share_config = {
            "common": {
                "bdSnsKey": {},
                "bdText": "",
                "bdMini": "2",
                "bdMiniList": false,
                "bdPic": "",
                "bdStyle": "0",
                "bdSize": "16"
            }, "share": {}
        };
        with (document) 0[(getElementsByTagName('head')[0] || body).
        appendChild(createElement('script')).
            src = 'http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='
            + ~(-new Date() / 36e5)];
    </script>
    {{ super() }}
    <script>new ClipboardJS('.c-btn');</script>
{% endblock %}